title:              Moosetechnology
email:              https://sympa.inria.fr/sympa/subscribe/moose
description:        Analyse and model your software system
author:             Moosetechnology
baseurl:            ""
url:                "https://modularmoose.org"

twitter_username:   moosetechnology
github_username:    moosetechnology

collections:
  posts:
    output: true
    permalink: /:collection/:name

tag_page_layout: tag_page
tag_page_dir: posts/tag
tag_permalink_style: pretty

# Build settings
markdown:           kramdown
highlighter: rouge
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
  - jekyll-spaceship
  - jekyll-seo-tag
  - jekyll-toc

# _config.yml
toc:
  list_id: my-toc-id # Default: "toc"
  list_class: my-list-class # Default: "section-nav"
  sublist_class: my-sublist-class # Default: no class for sublists
  item_class: my-item-class # Default: "toc-entry"
  item_prefix: item- # Default: "toc-":
